// render.mjs — turn a token map into the two artifacts: the interactive design.html and DESIGN.md.
import { fileURLToPath } from 'node:url';
import { read, path } from './util.mjs';
import { serializeRoot } from './tokens.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE = read(path.join(HERE, 'template.html'));
const MARKER = '/* __DESIGN_TOKENS__ */';

// Render the self-contained interactive style guide. The page's own background is var(--bg),
// so the preview literally matches the frontend's background color.
export function renderHtml(tokens) {
  return TEMPLATE.replace(MARKER, serializeRoot(tokens));
}

// Render DESIGN.md — the philosophy/rules (static) + a token mirror generated from the live names.
export function renderDesignMd(tokens) {
  const names = Object.keys(tokens);
  const has = (n) => names.includes(n);
  const mirror = [];
  const group = (label, list) => {
    const present = list.filter(has);
    if (present.length) mirror.push(`- **${label}:** ${present.map((n) => `\`${n}\``).join(', ')}.`);
  };
  group('Foundation', ['--bg', '--bg-2', '--panel', '--panel-2', '--inset', '--line', '--ink', '--ink-2', '--muted', '--faint']);
  group('Accent', ['--accent', '--accent-2', '--accent-ink']);
  group('Semantic', ['--success', '--warn', '--danger', '--info']);
  group('Type', ['--font-sans', '--font-mono', '--text-xs', '--text-sm', '--text-base', '--text-lg', '--text-xl', '--text-2xl', '--text-3xl', '--lh']);
  group('Space', ['--space-px', '--space-1', '--space-2', '--space-3', '--space-4', '--space-5', '--space-6', '--space-7', '--space-8']);
  group('Radius', ['--radius-sm', '--radius-md', '--radius-lg', '--radius-pill']);
  group('Elevation', ['--shadow-sm', '--shadow']);

  return `# DESIGN.md — design language (AI source of truth)

> Companion: **\`design.html\`** (interactive, human-viewable; its \`:root\` is the canonical token
> source). This file holds the **philosophy + rules** the AI applies on every UI task, plus a mirror
> of the token names. Values live in \`design.html\`; change them there or via \`design edit\`.

## 1. Principles (the judgment layer)
1. **Hierarchy by contrast, not weight-soup.** Establish level with size + color (\`--ink\` → \`--muted\` → \`--faint\`). One \`h1\` per view.
2. **One accent per view.** \`--accent\` carries the single most important action/state; everything else is neutral.
3. **Spacing is rhythm.** Use only the spacing scale; related things close, unrelated far.
4. **Elevation is light, not boxes.** Separate surfaces with \`--panel\`/\`--inset\` tints + a hairline \`--line\`; \`--shadow\` only when floating.
5. **Density with air.** Body text is \`--ink\` on \`--bg\`/\`--panel\` — never pure white on dark. Default line-height \`--lh\`.
6. **Motion is feedback, ≤150ms.** Confirm changes; respect \`prefers-reduced-motion\`.
7. **Color = meaning.** \`--success/--warn/--danger/--info\` are semantic, never decorative.

## 2. Application rules (do / don't)
- **Do** reference tokens (\`var(--…)\`) for every color, size, radius, shadow. **Don't** write a raw hex/px — \`design apply\` flags it.
- **Do** pick text by surface: \`--ink\` primary, \`--muted\` secondary, \`--faint\` hints. **Don't** drop below WCAG AA (4.5 body / 3 large).
- **Do** size from the type scale and shape from the radius scale. **Don't** invent intermediate values.
- **Do** keep one primary action per view styled with \`--accent\`. Secondary actions are neutral.
- **Voice:** plain, concise, active; sentence case; errors say what happened + the fix.

## 3. Token mirror (names only — values live in \`design.html\` \`:root\`)
${mirror.join('\n')}

---
*Generated by \`design create\`/\`get\`; tuned via \`design edit\`; rolled out with \`design apply\`.*
`;
}
